Repository Friends77/FRI-BACKEND, pull requests merged in 2024-12, with the labels that each got.

#30 Feature/profile
  friends_server/src/main/kotlin/com/friends/board/controller/BoardController.kt
  friends_server/src/main/kotlin/com/friends/board/entity/BoardEntities.kt
  friends_server/src/main/kotlin/com/friends/board/repository/BoardHashtagRepository.kt
  friends_server/src/main/kotlin/com/friends/board/repository/HashtagRepository.kt
  friends_server/src/main/kotlin/com/friends/board/service/BoardCommandService.kt
  friends_server/src/main/kotlin/com/friends/board/service/BoardQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/member/MemberExceptions.kt
  friends_server/src/main/kotlin/com/friends/member/entity/MemberEntities.kt
  friends_server/src/main/kotlin/com/friends/profile/ProfileExceptions.kt
  friends_server/src/main/kotlin/com/friends/profile/dto/ProfileDtos.kt
  friends_server/src/main/kotlin/com/friends/profile/entity/ProfileEntity.kt
  friends_server/src/main/kotlin/com/friends/profile/entity/ProfileEnums.kt
  friends_server/src/main/kotlin/com/friends/profile/repository/ProfileRepository.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileQueryService.kt
  friends_server/src/test/kotlin/com/friends/DBConnectionTest.kt
  friends_server/src/test/kotlin/com/friends/config/OAuth2PropertiesTest.kt
Labels: enhancement

#48 Fix/auth
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/jwt/AtRtService.kt
  friends_server/src/main/kotlin/com/friends/jwt/JwtService.kt
  friends_server/src/main/kotlin/com/friends/member/repository/MemberRepository.kt
  friends_server/src/main/kotlin/com/friends/security/AuthDtos.kt
  friends_server/src/main/kotlin/com/friends/security/controller/AuthController.kt
  friends_server/src/main/kotlin/com/friends/security/securityException/InvalidTokenException.kt
  friends_server/src/main/kotlin/com/friends/security/service/AuthService.kt
  friends_server/src/main/kotlin/com/friends/security/userDetails/CustomUserDetailsService.kt
  friends_server/src/test/kotlin/com/friends/jwt/AtRtServiceTest.kt
  friends_server/src/test/kotlin/com/friends/jwt/JwtServiceTest.kt
Labels: bug, enhancement

#42 Feature/board-test
  friends_server/src/main/kotlin/com/friends/board/BoardExceptions.kt
  friends_server/src/main/kotlin/com/friends/board/entity/BoardEntities.kt
  friends_server/src/main/kotlin/com/friends/board/repository/BoardHashtagRepository.kt
  friends_server/src/main/kotlin/com/friends/board/repository/HashtagRepository.kt
  friends_server/src/main/kotlin/com/friends/board/service/BoardCommandService.kt
  friends_server/src/main/kotlin/com/friends/board/service/BoardQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/test/kotlin/com/friends/board/BoardFixture.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/config/OAuth2PropertiesTest.kt
Labels: enhancement

#52 feature/convert-to-rdb
  docker-compose.yml
  friends_server/.gitignore
  friends_server/build.gradle.kts
  friends_server/docker-compose.yml
  friends_server/src/main/kotlin/com/friends/FriendsServerApplication.kt
  friends_server/src/main/kotlin/com/friends/chat/ChatException.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoom.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomCategoty.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomMember.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatSubjectCategory.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/Message.kt
  friends_server/src/main/kotlin/com/friends/common/entity/BaseMongoTimeEntity.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/config/MongoConfig.kt
  friends_server/src/main/resources/application-dev.yml
  friends_server/src/main/resources/application.yml
  friends_server/src/test/kotlin/com/friends/DBConnectionTest.kt
Labels: enhancement

#46 Feature/create_chat_room_swagger
  friends_server/src/main/kotlin/com/friends/board/controller/BoardController.kt
  friends_server/src/main/kotlin/com/friends/board/controller/BoardControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/ApiErrorCodeExamples.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/ApiExample.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/config/ApiDocsConfig.kt
  friends_server/src/main/kotlin/com/friends/config/SpringSecurityConfig.kt
  friends_server/src/main/kotlin/com/friends/email/EmailVerifyController.kt
  friends_server/src/main/kotlin/com/friends/email/EmailVerifyControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardQueryServiceTest.kt
Labels: enhancement

#45 Feature/create_chat_room_test
  friends_server/src/main/kotlin/com/friends/board/controller/BoardController.kt
  friends_server/src/main/kotlin/com/friends/board/controller/BoardControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/ApiErrorCodeExamples.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/ApiExample.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/config/ApiDocsConfig.kt
  friends_server/src/main/kotlin/com/friends/config/SpringSecurityConfig.kt
  friends_server/src/main/kotlin/com/friends/email/EmailVerifyController.kt
  friends_server/src/main/kotlin/com/friends/email/EmailVerifyControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/main/kotlin/com/friends/security/filter/JwtFilter.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomRepositoryKtTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/member/MemberFixture.kt
  friends_server/src/test/kotlin/com/friends/support/MockMvcHelper.kt
  friends_server/src/test/kotlin/com/friends/support/MutipartFileSupport.kt
  friends_server/src/test/kotlin/com/friends/support/annotation/ControllerTest.kt
  friends_server/src/test/kotlin/com/friends/support/annotation/RepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/support/config/KotestProjectConfig.kt
  friends_server/src/test/kotlin/com/friends/support/config/TestSpringSecurityConfig.kt
Labels: enhancement

#44 Feature/create chat room
  friends_server/src/main/kotlin/com/friends/board/controller/BoardController.kt
  friends_server/src/main/kotlin/com/friends/board/controller/BoardControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/ChatException.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomRequestDto.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomCategoty.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatSubjectCategory.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomCategoryRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatSubjectCategoryRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/MessageRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/ApiErrorCodeExamples.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/ApiExample.kt
  friends_server/src/main/kotlin/com/friends/common/swagger/config/ApiDocsConfig.kt
  friends_server/src/main/kotlin/com/friends/config/SpringSecurityConfig.kt
  friends_server/src/main/kotlin/com/friends/email/EmailVerifyController.kt
  friends_server/src/main/kotlin/com/friends/email/EmailVerifyControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/member/repository/MemberRepository.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/main/kotlin/com/friends/security/filter/JwtFilter.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomRepositoryKtTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/member/MemberFixture.kt
  friends_server/src/test/kotlin/com/friends/support/MockMvcHelper.kt
  friends_server/src/test/kotlin/com/friends/support/MutipartFileSupport.kt
  friends_server/src/test/kotlin/com/friends/support/annotation/ControllerTest.kt
  friends_server/src/test/kotlin/com/friends/support/annotation/RepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/support/config/KotestProjectConfig.kt
  friends_server/src/test/kotlin/com/friends/support/config/TestSpringSecurityConfig.kt
Labels: enhancement

#54 Featue/auth oauth2
  friends_server/gradlew
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/member/entity/MemberEntities.kt
  friends_server/src/main/kotlin/com/friends/member/repository/MemberRepository.kt
  friends_server/src/main/kotlin/com/friends/profile/entity/ProfileEntity.kt
  friends_server/src/main/kotlin/com/friends/security/AuthDtos.kt
  friends_server/src/main/kotlin/com/friends/security/controller/AuthController.kt
  friends_server/src/main/kotlin/com/friends/security/securityException/InvalidTokenException.kt
  friends_server/src/main/kotlin/com/friends/security/service/AuthService.kt
  friends_server/src/main/kotlin/com/friends/security/userDetails/CustomUserDetails.kt
  friends_server/src/test/kotlin/com/friends/board/BoardFixture.kt
Labels: enhancement

#61 Fix/cors error
  friends_server/.dockerignore
  friends_server/src/main/kotlin/com/friends/chat/entity/Message.kt
  friends_server/src/main/kotlin/com/friends/config/CorsConfig.kt
Labels: bug, enhancement

#60 Fix/invalid method
  friends_server/.dockerignore
  friends_server/src/main/kotlin/com/friends/chat/entity/Message.kt
Labels: bug, documentation

#59 feature/change_to_set
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomRequestDto.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatSubjectCategoryRepository.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/profile/entity/ProfileEntity.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
Labels: documentation

#68 Feat : KotestConfig 설정
  friends_server/src/test/kotlin/com/friends/board/service/BoardCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomRepositoryKtTest.kt
  friends_server/src/test/kotlin/com/friends/jwt/AtRtServiceTest.kt
  friends_server/src/test/kotlin/com/friends/jwt/JwtServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/service/ProfileCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/service/ProfileQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/security/filter/JwtFilterTest.kt
  friends_server/src/test/kotlin/com/friends/support/config/KotestProjectConfig.kt
Labels: enhancement

#69 Feature/get_chat_room
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomRequestDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/category/ChatSubjectCategoryResponse.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/mapper/ChatRoomResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoom.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomMember.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/chat/util/SliceChatRoomInfoResponseDto.kt
  friends_server/src/main/kotlin/com/friends/common/dto/SliceBaseResponse.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/mapper/SliceBaseResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/common/util/JdslUtil.kt
  friends_server/src/main/kotlin/com/friends/member/entity/MemberEntities.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomRepositoryKtTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/commonFixture.kt
  friends_server/src/test/kotlin/com/friends/member/MemberFixture.kt
Labels: enhancement

#75 Feature/profile location without postgis
  friends_server/src/main/kotlin/com/friends/profile/dto/ProfileDtos.kt
  friends_server/src/main/kotlin/com/friends/profile/entity/ProfileEntity.kt
  friends_server/src/main/kotlin/com/friends/profile/repository/ProfileRepository.kt
  friends_server/src/test/kotlin/com/friends/profile/ProfileFixture.kt
  friends_server/src/test/kotlin/com/friends/profile/repository/ProfileRepositoryTest.kt
Labels: enhancement

#76 Feature/register with profile
  friends_server/src/main/kotlin/com/friends/security/AuthDtos.kt
  friends_server/src/main/kotlin/com/friends/security/controller/AuthController.kt
  friends_server/src/main/kotlin/com/friends/security/service/AuthService.kt
Labels: enhancement

#89 Feat : Message 엔티티 분리
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoom.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/message/entity/Message.kt
  friends_server/src/main/kotlin/com/friends/message/repository/MessageRepository.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
Labels: documentation

#94 Feature/like chat room
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomLikeController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomLikeControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ToggleLikeResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomLike.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomLikeRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomLikeCommandService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/member/repository/MemberRepository.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomLikeControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomLikeRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomRepositoryKtTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomLikeCommandServiceTest.kt
Labels: enhancement

#97 feature/multi_part_form_data_converter
  friends_server/src/main/kotlin/com/friends/common/converter/MultipartJackson2HttpMessageConverter.kt
Labels: bug

#90 Feature/change dto return value
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomInfoResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/mapper/ChatRoomResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomCategory.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoomMember.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/entity/BaseTimeEntity.kt
  friends_server/src/main/kotlin/com/friends/common/util/JdslUtil.kt
  friends_server/src/main/kotlin/com/friends/message/entity/Message.kt
  friends_server/src/main/kotlin/com/friends/message/repository/MessageRepository.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/message/MessageFixture.kt
  friends_server/src/test/kotlin/com/friends/message/repository/MessageRepositoryTest.kt
Labels: enhancement

#104 Feature/get chat room info
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomInfoResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/mapper/ChatRoomResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomLikeRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomLikeCommandService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomLikeRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomLikeCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
Labels: enhancement

#109 fix/open_warn
  friends_server/src/main/kotlin/com/friends/message/entity/Message.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/message/MessageFixture.kt
Labels: bug

#111 feature/image_upload_and_get_url
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomInfoResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/image/S3ClientService.kt
Labels: enhancement
