Repository Friends77/FRI-BACKEND, pull requests merged in 2025-01, with the labels that each got.

#113 Feature/enter_chat_room
  friends_server/src/main/kotlin/com/friends/chat/ChatException.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/chat/websocket/ChatWebSocketHandler.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/config/InitDB.kt
  friends_server/src/main/kotlin/com/friends/config/ThreadConfig.kt
  friends_server/src/main/kotlin/com/friends/member/entity/MemberEntities.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
Labels: enhancement

#133 Feat : 에러 헨들러 추가 작성
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
Labels: bug

#122 feature/get_categories
  friends_server/src/main/kotlin/com/friends/board/service/BoardCommandService.kt
  friends_server/src/main/kotlin/com/friends/category/controller/CategoryController.kt
  friends_server/src/main/kotlin/com/friends/category/controller/CategoryControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/category/dto/CategoryInfoResponse.kt
  friends_server/src/main/kotlin/com/friends/category/dto/CategoryResponse.kt
  friends_server/src/main/kotlin/com/friends/category/entity/Category.kt
  friends_server/src/main/kotlin/com/friends/category/repository/CategoryRepository.kt
  friends_server/src/main/kotlin/com/friends/category/service/CategoryQueryService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/common/mapper/CommonMapper.kt
  friends_server/src/main/kotlin/com/friends/config/InitDB.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/main/kotlin/com/friends/security/service/AuthService.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/service/ProfileCommandServiceTest.kt
Labels: enhancement

#129 Feature/vote 엔티티
  friends_server/src/main/kotlin/com/friends/board/entity/VoteEntities.kt
Labels: enhancement

#121 feature/leave chat room(웹소켓 부분 변동에 따른 수정했습니다. 다시 리뷰주세여!)
  friends_server/src/main/kotlin/com/friends/chat/ChatException.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomCategoryRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/message/entity/Message.kt
  friends_server/src/main/kotlin/com/friends/message/repository/MessageRepository.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/message/repository/MessageRepositoryTest.kt
Labels: enhancement

#137 fix/remove_test_parameter
  friends_server/src/test/kotlin/com/friends/CommonFixture.kt
Labels: bug

#139 Fix/base_image_url
  friends_server/src/main/kotlin/com/friends/admin/AdminController.kt
  friends_server/src/main/kotlin/com/friends/admin/AdminControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/admin/AdminService.kt
  friends_server/src/main/kotlin/com/friends/admin/BaseImage.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/mapper/ChatRoomResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/image/S3ClientService.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
Labels: bug, enhancement

#144 fix/test
  friends_server/src/test/kotlin/com/friends/board/service/BoardCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/ProfileFixture.kt
  friends_server/src/test/kotlin/com/friends/profile/service/ProfileCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/support/MutipartFileSupport.kt
Labels: bug

#147 Feature/chat_room_create_search_conditions
  friends_server/src/main/kotlin/com/friends/admin/AdminController.kt
  friends_server/src/main/kotlin/com/friends/admin/AdminControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/RecommendationEnum.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberAgeRangeRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberGenderRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomRecommendationCriteriaService.kt
  friends_server/src/main/kotlin/com/friends/config/InitDB.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomRecommendationCriteriaServiceTest.kt
  friends_server/src/test/kotlin/com/friends/member/MemberFixture.kt
  friends_server/src/test/kotlin/com/friends/profile/ProfileFixture.kt
Labels: enhancement

#148 feature/member_forced_to_leave
  friends_server/src/main/kotlin/com/friends/chat/ChatException.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/message/entity/Message.kt
Labels: enhancement

#158 feature/add_chat_room_list_info
  friends_server/build.gradle.kts
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/mapper/ChatRoomResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/util/JdslUtil.kt
  friends_server/src/main/kotlin/com/friends/member/entity/MemberEntities.kt
  friends_server/src/main/kotlin/com/friends/profile/controller/ProfileController.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/ProfileFixture.kt
Labels: enhancement

#157 feat: 웹소켓 이미지 보내기
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatMessageDto.kt
  friends_server/src/main/kotlin/com/friends/chat/websocket/ChatWebSocketHandler.kt
  friends_server/src/main/kotlin/com/friends/image/controller/ImageController.kt
  friends_server/src/main/kotlin/com/friends/image/controller/ImageControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/image/service/ImageCommandService.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/repository/ProfileCategoryRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/profile/repository/ProfileRepositoryTest.kt
Labels: enhancement

#165 Feature/delete message
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatMessageDto.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/message/MessageException.kt
  friends_server/src/main/kotlin/com/friends/message/controller/MessageController.kt
  friends_server/src/main/kotlin/com/friends/message/controller/MessageControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/message/entity/Message.kt
  friends_server/src/main/kotlin/com/friends/message/service/MessageCommandService.kt
Labels: enhancement

#152 Feature/vote (service)
  friends_server/src/main/kotlin/com/friends/admin/BaseImageType.kt
  friends_server/src/main/kotlin/com/friends/board/dto/VoteDto.kt
  friends_server/src/main/kotlin/com/friends/board/entity/VoteEntities.kt
  friends_server/src/main/kotlin/com/friends/board/exception/BoardExceptions.kt
  friends_server/src/main/kotlin/com/friends/board/exception/VoteException.kt
  friends_server/src/main/kotlin/com/friends/board/repository/VoteOptionRepository.kt
  friends_server/src/main/kotlin/com/friends/board/repository/VoteRepository.kt
  friends_server/src/main/kotlin/com/friends/board/service/BoardCommandService.kt
  friends_server/src/main/kotlin/com/friends/board/service/BoardQueryService.kt
  friends_server/src/main/kotlin/com/friends/board/service/CommentCommandService.kt
  friends_server/src/main/kotlin/com/friends/board/service/CommentQueryService.kt
  friends_server/src/main/kotlin/com/friends/board/service/LikeCommandService.kt
  friends_server/src/main/kotlin/com/friends/board/service/VoteCommandService.kt
  friends_server/src/main/kotlin/com/friends/board/service/VoteQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/board/service/BoardQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/ProfileFixture.kt
Labels: enhancement

#171 친구와 같이 참여중인 채팅방 조회
  friends_server/CustomPostgresqlDockerfile
  friends_server/install-postgresql-extensions.sql
  friends_server/src/main/kotlin/com/friends/admin/AdminService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/config/IndexCreator.kt
  friends_server/src/main/kotlin/com/friends/friendship/repository/FriendShipRepository.kt
  friends_server/src/main/kotlin/com/friends/recommendation/service/GlobalRecommendationService.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/message/repository/MessageRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/profile/repository/ProfileRepositoryTest.kt
Labels: enhancement

#172 Feature/change_slice_to_list
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/config/InitDB.kt
  friends_server/src/test/kotlin/com/friends/alarm/repository/AlarmRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/profile/repository/ProfileCategoryRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/profile/repository/ProfileRepositoryTest.kt
Labels: enhancement

#187 feature/chat_room_member_information
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomLikeControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/mapper/ChatRoomResponseMapper.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/friendship/entity/FriendshipStatusEnums.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
  friends_server/src/test/kotlin/com/friends/member/MemberFixture.kt
Labels: enhancement

#177 feature/distributed_lock
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomLikeCommandService.kt
  friends_server/src/main/kotlin/com/friends/common/annotation/DistributedLock.kt
  friends_server/src/main/kotlin/com/friends/common/aop/AopForTransaction.kt
  friends_server/src/main/kotlin/com/friends/common/aop/DistributedLockAop.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/common/exception/RedisLockException.kt
  friends_server/src/main/kotlin/com/friends/common/key/PublicRedisKey.kt
  friends_server/src/test/kotlin/com/friends/aop/DistributedLockAopTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
Labels: enhancement

#191 Feature/specific member information in chat room
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomController.kt
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
Labels: enhancement

#192 Feature/add chat room description
  friends_server/docker-compose.yml
  friends_server/src/main/kotlin/com/friends/chat/controller/ChatRoomControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomRequestDto.kt
  friends_server/src/main/kotlin/com/friends/chat/dto/ChatRoomResponseDto.kt
  friends_server/src/main/kotlin/com/friends/chat/entity/ChatRoom.kt
  friends_server/src/main/kotlin/com/friends/chat/repository/ChatRoomMemberRepository.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomCommandService.kt
  friends_server/src/main/kotlin/com/friends/chat/service/ChatRoomQueryService.kt
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/config/InitDB.kt
  friends_server/src/main/kotlin/com/friends/recommendation/service/GlobalRecommendationService.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/chat/controller/ChatRoomControllerTest.kt
  friends_server/src/test/kotlin/com/friends/chat/repository/ChatRoomMemberRepositoryTest.kt
  friends_server/src/test/kotlin/com/friends/chat/service/ChatRoomQueryServiceTest.kt
Labels: enhancement

#180 fix/update_profile_requestboby
  friends_server/.gitignore
  friends_server/src/main/kotlin/com/friends/common/exception/ErrorCode.kt
  friends_server/src/main/kotlin/com/friends/common/exception/GlobalExceptionHandler.kt
  friends_server/src/main/kotlin/com/friends/image/ImageException.kt
  friends_server/src/main/kotlin/com/friends/image/S3ClientService.kt
  friends_server/src/main/kotlin/com/friends/image/service/ImageCommandService.kt
  friends_server/src/main/kotlin/com/friends/member/entity/MemberEntities.kt
  friends_server/src/main/kotlin/com/friends/profile/controller/ProfileController.kt
  friends_server/src/main/kotlin/com/friends/profile/controller/ProfileControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/profile/dto/ProfileDtos.kt
  friends_server/src/main/kotlin/com/friends/profile/service/ProfileCommandService.kt
  friends_server/src/test/kotlin/com/friends/chat/ChatFixture.kt
  friends_server/src/test/kotlin/com/friends/profile/ProfileFixture.kt
  friends_server/src/test/kotlin/com/friends/profile/service/ProfileCommandServiceTest.kt
  friends_server/src/test/kotlin/com/friends/support/MutipartFileSupport.kt
Labels: bug

#193 fix/register_profile_image
  friends_server/src/main/kotlin/com/friends/image/controller/ImageController.kt
  friends_server/src/main/kotlin/com/friends/security/AuthDtos.kt
  friends_server/src/main/kotlin/com/friends/security/controller/AuthController.kt
  friends_server/src/main/kotlin/com/friends/security/controller/AuthControllerSpec.kt
  friends_server/src/main/kotlin/com/friends/security/service/AuthService.kt
Labels: bug
